### PR TITLE
Use B+ Tree iterator instead of DFS to find scheduled jobs to be executed

### PR DESCRIPTION
**Pull request by lucastetreault**

### CODE REVIEW

**Review by Charlie-chenchrl — APPROVED** [review]
LGTM! the delay is significantly reduced!

**Comment by lovemai073** [comment]
Hi

I would like to know if this issue has been published on a specific version? or not yet published?
I tested on version 5.16.4 and it doesn't seem to be fixed.

Thank you.

**Comment by lucastetreault** [comment]
Hey @lovemai073, I just noticed this.. . I posted an answer here regarding my findings on 5.16.3 vs. 5.16.4: https://github.com/apache/activemq/pull/728

**Comment by lovemai073** [comment]
yes, I have see that.
I am also doing a test again....

**Pull request merged**
